#!/bin/bash
auth_file=${AUTH_FILE:-/root/.ssh/authorized_keys}
echo "# Generated by add_github_keys.sh... this file is overridden every boot" > $auth_file
IFS=',' read -ra github_names <<< "$GITHUB_USERS"
for name in "${github_names[@]}"; do
    echo "  * Adding public key of github user $name to file $auth_file";
    echo "
# User $name" >> $auth_file;
    curl -s "https://github.com/$name.keys" >> $auth_file;
done